<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Add to Wallet</h4>
        </div>
        <div class="modal-body">
           <form class="form-horizontal" role="form" id="form_wallet_add_form" action="<?=$this->_base_url;?>api/wallet/add/">
                <!-- Text input-->
                <div class="form-group">
                    <label for="card_amount" class="col-lg-4 control-label">Amount</label>
                    <div class="col-lg-8">
                        <div class="input-group">
                            <span class="input-group-addon">$</span>
                            <input id="card_amount" name="card_amount" type="text" class="form-control" autofocus="autofocus" value="50">
                            <span class="input-group-addon">.00</span>
                        </div>
                    </div>
                </div>
        
                <!-- Text input-->
                <div class="form-group">
                    <label for="card_name" class="col-lg-4 control-label">Name on Card</label>
                    <div class="col-lg-8">
                        <input id="card_name" name="card_name" type="text" placeholder="e.g. 'John Q. Public'" class="form-control" required="required" />
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label for="card_number" class="col-lg-4 control-label">Card Number</label>
                    <div class="col-lg-8">
                        <input id="card_number" name="card_number" type="text" placeholder="e.g. '4000-0000-0000-0002'" class="form-control" required="required" />
                        <br/>
                        <ul class="cards">
                            <li class="visa">Visa</li>
                            <li class="mastercard off">MasterCard</li>
                            <li class="discover off">Discover</li>
                            <li class="maestro off">Maestro</li>
                            <li class="visa_electron off">Visa Electron</li>
                        </ul>
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label for="card_expiry" class="col-lg-4 control-label">Expiry Date</label>
                    <div class="col-lg-8">
                        <input id="card_expiry" name="card_expiry" type="text" placeholder="e.g. '07/2015'" class="form-control" required="required" />
                    </div>
                </div>
               

                 <!-- Text input-->
                <div class="form-group">
                    <label for="card_name" class="col-lg-4 control-label">CVV</label>
                    <div class="col-lg-8">
                        <input id="card_cvv" name="card_cvv" type="text" placeholder="e.g. '567'" class="form-control" required="required"  />
                    </div>
                </div>
             </form>
            
        </div>
        <div class="modal-footer">
            <div id="form_add_wallet_status"></div>
            <button id="btnCancel" name="btnCancel" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button id="btnSave" name="btnSave" class="btn btn-success" onclick="form_submit()">Add</button>
        </div>
    </div><!-- /.modal-content -->
    
    </form>
    
</div><!-- /.modal-dialog -->

<style>
.cards {
    overflow: hidden
}
.cards li {
    -webkit-transition: all .2s;
    -moz-transition: all .2s;
    -ms-transition: all .2s;
    -o-transition: all .2s;
    transition: all .2s;
    background-image: url(<?=$this->_base_url;?>assets/images/card_logos.png);
    background-position: 0 0;
    float: left;
    height: 32px;
    margin-right: 8px;
    text-indent: -9999px;
    width: 51px
}
.cards li: last-child {
    margin-right: 0
}
.cards .visa_electron {
    background-position: 204px 0
}
.cards .mastercard {
    background-position: 153px 0
}
.cards .maestro {
    background-position: 102px 0
}
.cards .discover {
    background-position: 51px 0
}
.cards .visa.off {
    background-position: 0 32px
}
.cards .visa_electron.off {
    background-position: 204px 32px
}
.cards .mastercard.off {
    background-position: 153px 32px
}
.cards .maestro.off {
    background-position: 102px 32px
}
.cards .discover.off {
    background-position: 51px 32px
}
form input.valid {
    background: url(<?=$this->_base_url;?>assets/images/tick.png) right center no-repeat;
}
</style>

<script src="<?=$this->_base_url;?>assets/js/jquery.creditcardvalidator.js"></script>
<script>
    // Generated by CoffeeScript 1.4.0
(function () {
    $(function () {
        $(".demo .numbers li").wrapInner('<a href="#"></a>').click(function (e) {
            e.preventDefault();
            return $("#card_number").val($(this).text()).trigger("input")
        });
        $(".vertical.maestro").hide().css({
            opacity: 0
        });
        return $("#card_number").validateCreditCard(function (e) {
            if (e.card_type == null) {
                $(".cards li").removeClass("off");
                $("#card_number").removeClass("valid");
                $(".vertical.maestro").slideUp({
                    duration: 200
                }).animate({
                    opacity: 0
                }, {
                    queue: !1,
                    duration: 200
                });
                return
            }
            $(".cards li").addClass("off");
            $(".cards ." + e.card_type.name).removeClass("off");
            e.card_type.name === "maestro" ? $(".vertical.maestro").slideDown({
                duration: 200
            }).animate({
                opacity: 1
            }, {
                queue: !1
            }) : $(".vertical.maestro").slideUp({
                duration: 200
            }).animate({
                opacity: 0
            }, {
                queue: !1,
                duration: 200
            });
            return e.length_valid && e.luhn_valid ? $("#card_number").addClass("valid") : $("#card_number").removeClass("valid")
        }, {
            accept: ["visa", "visa_electron", "mastercard", "maestro", "discover"]
        })
    })
}).call(this);


    function form_submit() {
        var form = $('form#form_wallet_add_form');
        $.ajax( {
               type: "POST",
               url: form.attr( 'action' ),
               data: form.serialize(),
               dataType: "json",
               success: function( response ) {
               
               if(response.success==true) {
               window.location.href = "<?=$this->_base_url;?>wallet";
               } else {
               $('#form_add_wallet_status').text(response.reason);
               }
               console.log( response );
               }
               } );
    }
    
    </script>
